---
apiVersion: litmuschaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: kubernetes
  version: 0.1.0
  annotations:
    categories: Kubernetes
    chartDescription: Injects kubernetes chaos experiment
    executionPlane: "kubernetes"
spec:
  displayName: Kubernetes
  categoryDescription: >
    Kubernetes is an open-source system for automating deployment, scaling, and management of containerized applications. It groups containers that make up an application into logical units for easier management and discovery. It will install all the experiments which can be used to inject chaos into containerized applications.
  faults:
    - name: http-delay
      description: It injects Istio http-delay chaos in a Kubernetes namespace.
      displayName: "Http Delay"
  keywords:
    - Kubernetes
  maintainers:
    - name: ksatchit
      email: karthik.s@harness.io
  minKubeVersion: 1.12.0
  links:
    - name: Kubernetes Website
      url: https://kubernetes.io
    - name: Source Code
      url: https://github.com/kubernetes/kubernetes
    - name: Kubernetes Slack
      url: https://slack.kubernetes.io/
    - name: Documentation
      url: https://litmuschaos.github.io/litmus/experiments/categories/contents/#kubernetes
  icon:
    - url: https://github.com/litmuschaos/chaos-charts/blob/master/faults/kubernetes/icons/kubernetes.png
      mediatype: image/png
