---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: istio-http-latency-chaos
  namespace: default
spec:
  # It can be active/stop
  engineState: 'active'
  chaosServiceAccount: istio-http-latency-sa
  experiments:
    - name: istio-http-latency
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: "60"

            - name: NAMESPACE
              value: ""

            - name: VIRTUAL_SERVICE
              value: ""

            - name: DESTINATION_HOSTS
              value: ""

            - name: DESTINATION_PORTS
              value: ""

            - name: MATCH_HEADERS
              value: ""

            - name: MATCH_HEADERS_SCHEME
              value: ""

            - name: MATCH_URIS
              value: ""

            - name: MATCH_URIS_SCHEME
              value: ""

            - name: REQUEST_AFFECTED_PERC
              value: "100"

            - name: LATENCY
              value: "2000"
